apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-capstone
  labels:
    app: cloud-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-capstone
  template:
    metadata:
      labels:
        app: cloud-capstone
    spec:
      containers:
      - name: cloud-capstone
        image: ta9i/cloud-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 8080