apiVersion: v1
kind: Service
metadata:
  name: cloud-capstone
  labels:
    app: cloud-capstone
  
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: cloud-capstone


    